In [10]:
import numpy as np

varios = np.zeros((3,4))
uno = np.ones(4)
incremento = 1
for i in varios:
    for j in range(len(i)):
        i[j] = incremento
        incremento += 1
print(varios)
print(uno)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
[1. 1. 1. 1.]


In [15]:
varios2 = varios + uno
print(varios2)

[[ 2.  3.  4.  5.]
 [ 6.  7.  8.  9.]
 [10. 11. 12. 13.]]


In [16]:
varios2 -= uno
print(varios2)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
